---
title: "pdb_clusters"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(reshape2)
library(stringr)
library(ggplot2)
library(RColorBrewer)
select = dplyr::select 
```

```{r}
hs.unpaired.alpha = fread('position_analysis/TRAV_HomoSapiens.unpaired.txt')
hs.unpaired.beta = fread('position_analysis/TRBV_HomoSapiens.unpaired.txt')
```
```{r}
hs.unpaired.alpha
```

```{r, fig.width=8}
ggplot(data = hs.unpaired.alpha %>% group_by(cluster) %>% mutate(totsum = sum(count)), 
       aes(cluster, count)) + 
  geom_col(aes(fill = id), show.legend = F) +
  geom_text(aes(label = id, group = id), position = position_stack(vjust = 0.5)) +
  theme_bw() + 
  labs(title="V gene representation in structures",
        subtitle=paste0("specie: ", "HomoSapiens",
                       "; chain: ", "alpha"),
        x="Clusters",
        y="Number of structures") +
    theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20), 
        plot.title=element_text(size=28),
        plot.subtitle=element_text(size=21))

#ggsave('TRAV_HomoSapiens.unpaired.png')
```

```{r, fig.width=8}
ggplot(data = hs.unpaired.beta %>% group_by(cluster) %>% mutate(totsum = sum(count)), 
       aes(cluster, hs.unpaired.alpha$count)) + 
  geom_col(aes(fill = id), show.legend = F) +
  geom_text(aes(label = id, group = id), position = position_stack(vjust = 0.5)) +
  theme_bw() + 
  labs(title="V gene representation in structures",
        subtitle=paste0("specie: ", "HomoSapiens",
                       "; chain: ", "beta"),
        x="Clusters",
        y="Number of structures") +
    theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20), 
        plot.title=element_text(size=28),
        plot.subtitle=element_text(size=21))

#ggsave('TRBV_HomoSapiens.unpaired.png')
```

```{r}
hs.paired = fread('position_analysis/TRV_HomoSapiens.paired.txt')
```



```{r, fig.width=8}
ggplot(data = hs.paired %>% group_by(alpha_beta_clusters) %>% mutate(totsum = sum(count)), aes(alpha_beta_clusters, hs.paired$count)) + 
  #facet_grid(~cluster) +
  geom_col(aes(fill=alpha_beta_clusters), color='black', show.legend = F) +
  #geom_text(aes(label=alpha_beta), position = position_stack(vjust=0.5)) +
  theme_bw() +
  labs(title="V gene representation in structures",
        subtitle=paste0("specie: ", "HomoSapiens",
                       "; chains: ", "paired"),
        x="Clusters",
        y="Number of structures") +
    theme(axis.text=element_text(size=8.5),
        axis.title=element_text(size=20), 
        axis.text.y=element_text(size=20),
        plot.title=element_text(size=28),
        plot.subtitle=element_text(size=21))

#ggsave('TRV_HomoSapiens.paired.png')
```
